//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_vrFps_Grip;
        
        private static SteamVR_Action_Boolean p_vrFps_Trigger;
        
        private static SteamVR_Action_Boolean p_vrFps_Menu;
        
        private static SteamVR_Action_Boolean p_vrFps_Touchpad;
        
        private static SteamVR_Action_Vector2 p_vrFps_TouchpadAxis;
        
        private static SteamVR_Action_Single p_vrFps_TriggerAxis;
        
        private static SteamVR_Action_Skeleton p_vrFps_RightSkel;
        
        private static SteamVR_Action_Skeleton p_vrFps_LeftSkel;
        
        private static SteamVR_Action_Pose p_vrFps_LeftPose;
        
        private static SteamVR_Action_Pose p_vrFps_RightPose;
        
        private static SteamVR_Action_Boolean p_vrFps_A;
        
        private static SteamVR_Action_Boolean p_vrFps_B;
        
        private static SteamVR_Action_Boolean p_vrFps_Joystick;
        
        private static SteamVR_Action_Vector2 p_vrFps_JoystickAxis;
        
        public static SteamVR_Action_Boolean vrFps_Grip
        {
            get
            {
                return SteamVR_Actions.p_vrFps_Grip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vrFps_Trigger
        {
            get
            {
                return SteamVR_Actions.p_vrFps_Trigger.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vrFps_Menu
        {
            get
            {
                return SteamVR_Actions.p_vrFps_Menu.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vrFps_Touchpad
        {
            get
            {
                return SteamVR_Actions.p_vrFps_Touchpad.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 vrFps_TouchpadAxis
        {
            get
            {
                return SteamVR_Actions.p_vrFps_TouchpadAxis.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Single vrFps_TriggerAxis
        {
            get
            {
                return SteamVR_Actions.p_vrFps_TriggerAxis.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Skeleton vrFps_RightSkel
        {
            get
            {
                return SteamVR_Actions.p_vrFps_RightSkel.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton vrFps_LeftSkel
        {
            get
            {
                return SteamVR_Actions.p_vrFps_LeftSkel.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Pose vrFps_LeftPose
        {
            get
            {
                return SteamVR_Actions.p_vrFps_LeftPose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Pose vrFps_RightPose
        {
            get
            {
                return SteamVR_Actions.p_vrFps_RightPose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Boolean vrFps_A
        {
            get
            {
                return SteamVR_Actions.p_vrFps_A.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vrFps_B
        {
            get
            {
                return SteamVR_Actions.p_vrFps_B.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vrFps_Joystick
        {
            get
            {
                return SteamVR_Actions.p_vrFps_Joystick.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 vrFps_JoystickAxis
        {
            get
            {
                return SteamVR_Actions.p_vrFps_JoystickAxis.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.vrFps_Grip,
                    SteamVR_Actions.vrFps_Trigger,
                    SteamVR_Actions.vrFps_Menu,
                    SteamVR_Actions.vrFps_Touchpad,
                    SteamVR_Actions.vrFps_TouchpadAxis,
                    SteamVR_Actions.vrFps_TriggerAxis,
                    SteamVR_Actions.vrFps_RightSkel,
                    SteamVR_Actions.vrFps_LeftSkel,
                    SteamVR_Actions.vrFps_LeftPose,
                    SteamVR_Actions.vrFps_RightPose,
                    SteamVR_Actions.vrFps_A,
                    SteamVR_Actions.vrFps_B,
                    SteamVR_Actions.vrFps_Joystick,
                    SteamVR_Actions.vrFps_JoystickAxis};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.vrFps_Grip,
                    SteamVR_Actions.vrFps_Trigger,
                    SteamVR_Actions.vrFps_Menu,
                    SteamVR_Actions.vrFps_Touchpad,
                    SteamVR_Actions.vrFps_TouchpadAxis,
                    SteamVR_Actions.vrFps_TriggerAxis,
                    SteamVR_Actions.vrFps_RightSkel,
                    SteamVR_Actions.vrFps_LeftSkel,
                    SteamVR_Actions.vrFps_LeftPose,
                    SteamVR_Actions.vrFps_RightPose,
                    SteamVR_Actions.vrFps_A,
                    SteamVR_Actions.vrFps_B,
                    SteamVR_Actions.vrFps_Joystick,
                    SteamVR_Actions.vrFps_JoystickAxis};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[0];
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[0];
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.vrFps_LeftPose,
                    SteamVR_Actions.vrFps_RightPose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.vrFps_Grip,
                    SteamVR_Actions.vrFps_Trigger,
                    SteamVR_Actions.vrFps_Menu,
                    SteamVR_Actions.vrFps_Touchpad,
                    SteamVR_Actions.vrFps_A,
                    SteamVR_Actions.vrFps_B,
                    SteamVR_Actions.vrFps_Joystick};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.vrFps_TriggerAxis};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.vrFps_TouchpadAxis,
                    SteamVR_Actions.vrFps_JoystickAxis};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    SteamVR_Actions.vrFps_RightSkel,
                    SteamVR_Actions.vrFps_LeftSkel};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.vrFps_Grip,
                    SteamVR_Actions.vrFps_Trigger,
                    SteamVR_Actions.vrFps_Menu,
                    SteamVR_Actions.vrFps_Touchpad,
                    SteamVR_Actions.vrFps_TouchpadAxis,
                    SteamVR_Actions.vrFps_TriggerAxis,
                    SteamVR_Actions.vrFps_A,
                    SteamVR_Actions.vrFps_B,
                    SteamVR_Actions.vrFps_Joystick,
                    SteamVR_Actions.vrFps_JoystickAxis};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_vrFps_Grip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VrFps/in/Grip")));
            SteamVR_Actions.p_vrFps_Trigger = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VrFps/in/Trigger")));
            SteamVR_Actions.p_vrFps_Menu = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VrFps/in/Menu")));
            SteamVR_Actions.p_vrFps_Touchpad = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VrFps/in/Touchpad")));
            SteamVR_Actions.p_vrFps_TouchpadAxis = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/VrFps/in/TouchpadAxis")));
            SteamVR_Actions.p_vrFps_TriggerAxis = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/VrFps/in/TriggerAxis")));
            SteamVR_Actions.p_vrFps_RightSkel = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/VrFps/in/RightSkel")));
            SteamVR_Actions.p_vrFps_LeftSkel = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/VrFps/in/LeftSkel")));
            SteamVR_Actions.p_vrFps_LeftPose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/VrFps/in/LeftPose")));
            SteamVR_Actions.p_vrFps_RightPose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/VrFps/in/RightPose")));
            SteamVR_Actions.p_vrFps_A = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VrFps/in/A")));
            SteamVR_Actions.p_vrFps_B = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VrFps/in/B")));
            SteamVR_Actions.p_vrFps_Joystick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VrFps/in/Joystick")));
            SteamVR_Actions.p_vrFps_JoystickAxis = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/VrFps/in/JoystickAxis")));
        }
    }
}
