//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VrFps : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.vrFps_Grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean Trigger
        {
            get
            {
                return SteamVR_Actions.vrFps_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.vrFps_Menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean Touchpad
        {
            get
            {
                return SteamVR_Actions.vrFps_Touchpad;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TouchpadAxis
        {
            get
            {
                return SteamVR_Actions.vrFps_TouchpadAxis;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerAxis
        {
            get
            {
                return SteamVR_Actions.vrFps_TriggerAxis;
            }
        }
        
        public virtual SteamVR_Action_Skeleton RightSkel
        {
            get
            {
                return SteamVR_Actions.vrFps_RightSkel;
            }
        }
        
        public virtual SteamVR_Action_Skeleton LeftSkel
        {
            get
            {
                return SteamVR_Actions.vrFps_LeftSkel;
            }
        }
        
        public virtual SteamVR_Action_Pose LeftPose
        {
            get
            {
                return SteamVR_Actions.vrFps_LeftPose;
            }
        }
        
        public virtual SteamVR_Action_Pose RightPose
        {
            get
            {
                return SteamVR_Actions.vrFps_RightPose;
            }
        }
        
        public virtual SteamVR_Action_Boolean A
        {
            get
            {
                return SteamVR_Actions.vrFps_A;
            }
        }
        
        public virtual SteamVR_Action_Boolean B
        {
            get
            {
                return SteamVR_Actions.vrFps_B;
            }
        }
        
        public virtual SteamVR_Action_Boolean Joystick
        {
            get
            {
                return SteamVR_Actions.vrFps_Joystick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 JoystickAxis
        {
            get
            {
                return SteamVR_Actions.vrFps_JoystickAxis;
            }
        }
    }
}
